import 'dart:io';
import 'dart:convert';

import 'package:persian_localizer/src/utils/TextUtils.dart';


/// Generates Dart localization class
void generateLocalizationClass(List<String> keys) {
  print('📝 Generating localization class...');

  final buffer = StringBuffer();

  buffer.writeln('''
// GENERATED FILE - DO NOT EDIT
// This file was generated by the Persian String Localization Tool

import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  // Translation maps
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
''');

  // Load existing English translations for context
  final enArbFile = File('l10n/intl_en.arb');
  final enArb = enArbFile.existsSync()
      ? json.decode(enArbFile.readAsStringSync()) as Map<String, dynamic>
      : {};

  // Add English translations
  for (final key in keys) {
    final existingTranslation = enArb[key];
    if (existingTranslation != null) {
      buffer.writeln(
          "      '$key': '${escapeDartString(existingTranslation.toString())}',");
    } else {
      buffer.writeln("      '$key': '$key', // TODO: Translate to English");
    }
  }

  buffer.writeln('''
    },
    'fa': {
''');

  // Add Persian translations
  final faArbFile = File('l10n/intl_fa.arb');
  final faContent = faArbFile.readAsStringSync();
  final faMap = json.decode(faContent) as Map<String, dynamic>;

  for (final entry in faMap.entries) {
    buffer.writeln(
        "      '${entry.key}': '${escapeDartString(entry.value.toString())}',");
  }

  buffer.writeln('''
    },
  };

  String _getText(String key) {
    final languageCode = locale.languageCode;
    
    // Try exact match
    if (_localizedValues[languageCode]?[key] != null) {
      return _localizedValues[languageCode]![key]!;
    }
    
    // Fallback to English
    if (_localizedValues['en']?[key] != null) {
      return _localizedValues['en']![key]!;
    }
    
    // Fallback to key itself
    return key;
  }
''');

  // Generate getter methods for each key
  for (final key in keys) {
    final methodName = keyToMethodName(key);
    buffer.writeln('''
  String get $methodName => _getText('$key');
''');
  }

  buffer.writeln('''
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'fa'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
''');

  final outputDir = Directory('lib/generated');
  outputDir.createSync(recursive: true);

  final outputFile = File('lib/generated/localizations.dart');
  outputFile.writeAsStringSync(buffer.toString());

  print('✅ Generated: lib/generated/localizations.dart');
  print('   - ${keys.length} translation keys');
  print('\n📋 Next steps to use in your app:');
  print('''
  1. Add to your MaterialApp/CupertinoApp:
     localizationsDelegates: [
       AppLocalizations.delegate,
       GlobalMaterialLocalizations.delegate,
       GlobalWidgetsLocalizations.delegate,
     ],
     supportedLocales: [
       Locale('en'),
       Locale('fa'),
     ],
  
  2. Import the generated file:
     import 'generated/localizations.dart';
  
  3. Use in your widgets:
     Text(AppLocalizations.of(context).fa1)
  ''');
}